<?php
/**
 * Created by PhpStorm.
 * User: onwer
 * Date: 2018/4/11
 * Time: 18:41
 */

namespace module\task\status;


use biz\Session;
use CC\action\SaveAction;
use CC\db\base\select\ItemModel;
use CC\db\base\select\ListModel;
use CC\util\common\widget\form\creator\PostNamesCreator;
use CC\util\common\widget\form\IFormViewBuilder;
use CC\util\common\widget\form\IInput;
use CC\util\common\widget\form\IntInput;
use CC\util\common\widget\form\TextAreaInput;
use CC\util\common\widget\form\TextInput;
use module\notice\index\server\NoticeBeginTransaionServer;
use module\task\status\server\TaskOpServer;

class TaskStatusAddopAdminAction extends SaveAction implements IFormViewBuilder
{

    public $task_id;
    /**
     * @return string "name,pass"
     */
    protected function getPostNames()
    {
        return PostNamesCreator::create($this);
    }
    protected function getTable()
    {
        return 'task_op';
    }

    public function getIsLayout()
    {
        return false;
    }

    protected function onBeforeSave(&$data)
    {
        $re = ItemModel::make('task_op')
            ->addColumnsCondition(array('task_id'=>$this->task_id))
            ->order('id desc')
            ->execute();
        if ($re){
            $data['exp'] = intval($data['exp']) < intval($re['exp']) ?  $re['exp'] : $data['exp'];
        }

        unset($re);
        $data['content'] = Session::getName(). ' 修改任务进度,<br>备注: ' . $data['content'];
        $data['uid'] = Session::getUserID();
        $data['op_type'] = '0';
        $data['time'] = time();
        $data['task_id'] = $this->task_id;
    }

    protected function onAfterSave($data)
    {
        $oop = \CModel::model()->beginTransaction();
        TaskOpServer::updateCurProgress($this->task_id,$data['content']);
        NoticeBeginTransaionServer::getDatas(
            array_merge((array)ItemModel::make('task')->addColumnsCondition(['id' => $data['task_id']])->execute(), $data),
            'create', explode(',', $data['content'])[count(explode(',', $data['content']))-1]);
        $oop->commit();

    }
    protected function onSaveExecute($data)
    {
        return parent::onSaveExecute($data); // TODO: Change the autogenerated stub
    }

    /**
     * @return  IInput[]
     */
    public function createFormInputs()
    {
        $placeHolder = 0;
        $re = ItemModel::make('task_op')
            ->addColumnsCondition(array('task_id'=>$this->task_id))
            ->order('id desc')
            ->execute();
        if ($re){
            $placeHolder = $re['exp'];
        }
        return [
            (new IntInput('exp', '进度指数', ['must',['int','min'=>'0', 'max'=>100]]))->setExtrainfo('%')->setPlaceHolder($placeHolder),
    new TextAreaInput('content','描述','0',['must']),
        ];
    }


}