<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/4/13
 * Time: 12:08
 */

namespace module\project\manage;


use CC\action\module\basic\dept\enum\DeptEnum;
use CC\action\module\basic\tree\DeptTreeJsData;
use CC\action\module\basic\tree\UserDeptTreeJsData;
use CC\action\SaveAction;
use CC\util\common\widget\form\creator\PostNamesCreator;
use CC\util\common\widget\form\EmptyInput;
use CC\util\common\widget\form\FloatInput;
use CC\util\common\widget\form\IFormViewBuilder;
use CC\util\common\widget\form\IInput;
use CC\util\common\widget\form\SelectInput;
use CC\util\common\widget\form\SubmitInput;
use CC\util\common\widget\form\TextInput;
use CC\util\common\widget\form\TreeInput;
use module\project\manage\enum\IsmainTypeEnum;
use module\project\manage\form\OnlyInput;
use module\project\manage\server\ProjectMember;

class ProjectManageDutyAdminAction extends SaveAction implements IFormViewBuilder
{
    protected function getTable()
    {
        return 'project'; // TODO: Change the autogenerated stub
    }

    /**
     * @return string "name,pass"
     */
    protected function getPostNames()
    {
        return PostNamesCreator::create($this);
    }

    protected function getDetData()
    {
        $data = parent::getDetData();
        $data['uids'] = ProjectMember::projectmemberinfo($data['id']);
        return $data; // TODO: Change the autogenerated stub
    }




    /**
     * @return  IInput[]
     */
    public function createFormInputs()
    {

        return [];// TODO: Implement createFormInputs() method.
    }



    public function getIsLayout()
    {
        return false;
    }


    protected function onBeforeSave(&$data)
    {
        return parent::onBeforeSave($data); // TODO: Change the autogenerated stub
    }
//    protected function onAfterSave($data)
//    {
//        return parent::onAfterSave($data); // TODO: Change the autogenerated stub
//    }


}
