<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/4/15
 * Time: 11:01
 */

namespace module\project\manage;



use CC\action\SaveAction;
use CC\db\base\update\UpdateModel;
use CJsonData;
use CRenderData;
use CRequest;


class ProjectManageDataupdateAdminAction extends \CAction
{


    protected function getTable()
    {
        return 'project_user'; // TODO: Change the autogenerated stub
    }


    public function execute(CRequest $request)
    {

        if ($request->isAjax()) {
            $data = $this->getDatas($request);
            $arr[$data['key']] = $data['val'];
        }

        $relt = UpdateModel::make('project_user')
            ->addColumnsCondition(['uid' => $data['uid'], 'project_id' => $data['project_id']])
            ->addData([$data['key'] => $arr[$data['key']]])->execute();
        return new CJsonData([$relt]);
         // TODO: Change the autogenerated stub
    }



    private function getDatas($request)
    {
        $data['project_id'] = $request->getParams('pro_id');
        $data['key'] = $request->getParams('key');
        $data['uid'] = $request->getParams('uid');
        $data['val'] = $request->getParams('val');

        return $data; // TODO: Change the autogenerated stub
    }
}
